# Generated by Django 4.2.4 on 2023-08-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_hirer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_jobseeker',
        ),
    ]
